name: Publish Docker Image 
on: [push]
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    defaults:
      steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: 'Build Inventory Image'
          run: |
            docker build . --tag ghcr.io/ngn13/ezcat:latest
            docker push ghcr.io/ngn13/ezcat:latest
